### PR TITLE
Adding a full click-through unittest of running an InsertionLoss measurement with simulated instruments

### PR DESCRIPTION
**Pull request by marcoep**
This PR tries to add a full click-through unittest of the basic InsertionLossSweep measurement within the tkinter GUI.

### CODE REVIEW

**Comment by marcoep** [comment]
@boris-vukovic ready for review!

**Review by boris-vukovic — CHANGES_REQUESTED** [review]
requirements.txt is missing package pytest to run the test

**Comment by marcoep** [comment]
@maltewae What do you think about Boris' proposition? How is it usually solved in other packages that you include the packages for testing in requriements.txt?

Should we make an extra requirements_testing.txt? Or should we just include pytest in the "live" requirements.txt?

**Comment by maltewae** [comment]
@marcoep I would suggest to create a second dependency file for the testing environment to keep the production deps small. We could also use the [tox.ini](https://github.com/LabExT/LabExT/blob/main/tox.ini) for that, but then we would always have to run the tests locally via Tox.

**Comment by marcoep** [comment]
@boris-vukovic should be ready :) we moved the testing requirements to its separate file

**Review by boris-vukovic — APPROVED** [review]

**Pull request merged**
